"""baseline schema with hashed_password

Revision ID: 147d41164e1a
Revises: 
Create Date: 2026-08-27 23:39:08.194542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147d41164e1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Cart', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Cart', 'user_profile', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    op.drop_column('Cart', 'users_id')
    # ### end Alembic commands ###
