"""schema with hashed_password

Revision ID: 602c640fa726
Revises: 147d41164e1a
Create Date: 2026-08-28 00:23:38.289752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602c640fa726'
down_revision: Union[str, Sequence[str], None] = '147d41164e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'hashed_password')
    # ### end Alembic commands ###
